### ISSUE TITLE
vehicles go slow

### ISSUE THREAD

**Issue by skelegamerYT11** [SBDPlugins/Issues-VehiclesPlus#147]
I have a bug on VehiclePlus Pro, the vehicles are moving very slowly. How can I solve this?

The server is Spigot

**Comment by stijnb1234** [comment]
Please provide more info / a video.

**Comment by skelegamerYT11** [comment]
https://user-images.githubusercontent.com/127677552/226123593-7be47d7b-19e5-44b9-a18d-2a7f5384a647.mp4

**Comment by stijnb1234** [comment]
If you are using Paper, make sure that `armor-stands-tick` is set to `true` in your paper.yml file. If not, you should get an error in console. Please send it.

**Comment by skelegamerYT11** [comment]
https://user-images.githubusercontent.com/127677552/226170253-ec446180-dce8-45df-8649-da4925198c8a.mp4

**Comment by skelegamerYT11** [comment]
I don't use paper

**Comment by stijnb1234** [comment]
Please move and then send your `logs/latest.log`.

**Comment by skelegamerYT11** [comment]
[latest.log](https://github.com/SBDPlugins/Issues-VehiclesPlus/files/11010780/latest.log)

**Comment by stijnb1234** [comment]
I'm unsure why this happens. Probably another plugin is interfering with the VehiclesPlus key handling (by ProtocolLib). I recommend trying to disable plugins step-by-step until you are only left with the required plugins for VehiclesPlus. After you have removed a plugin, try if the problem is fixed every time.

**Comment by stijnb1234** [comment]
**Please do not use leaked plugins, it's piracy! I won't help you further, because of that.**
